### ISSUE TITLE
Can't run latest update

### ISSUE THREAD

**Issue by dppeak** [DeeeeLAN/homebridge-sleepiq#27] opened 2020-09-18 02:33 UTC
Updated to new release and seeing the following error

`[9/17/2020, 9:29:30 PM] ReferenceError: callback is not defined
    at API.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/API.js:501:5)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:76:39)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-sleepiq/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[9/17/2020, 9:29:30 PM] Got SIGTERM, shutting down Homebridge...`

**Comment by DeeeeLAN** [comment] 2020-09-18 02:35
Which version are you running? I think I fixed that bug earlier today.

**Comment by dppeak** [comment] 2020-09-18 02:36
Just updated to 4.0.

**Comment by dppeak** [comment] 2020-09-18 02:37
Tried uninstalling and then installing it again as well.

**Comment by DeeeeLAN** [comment] 2020-09-18 02:44
Okay, I will get it fixed tonight. I know what the problem is.

**Comment by dppeak** [comment] 2020-09-18 02:45
thanks....i'm excited to try the lights functionality

**Comment by DeeeeLAN** [comment] 2020-09-18 03:53
Should be fixed in 8c7c33a.

**Closed as completed by DeeeeLAN** 2020-09-18 03:53 UTC
Labels: bug
