### ISSUE TITLE
Error messages after the latest Homebridge updates

### ISSUE THREAD

**Issue by dikodahan** [DeeeeLAN/homebridge-sleepiq#21] opened 2020-05-23 20:24 UTC
My Homebridge installation has started throwing out these error messages after a few recent regular HB updates:
`(node:10191) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
    at new StatusCodeError (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sleepiq/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:10191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 210)`

**Comment by dikodahan** [comment] 2020-06-16 12:42
Any updates on this?

**Comment by DeeeeLAN** [comment] 2020-06-18 17:20
I haven't looked into it yet. I don't think mine has been working lately either so it might be related, but I haven't had time to look into anything.

**Comment by randymassey** [comment] 2020-06-25 08:56
I can add to these messages in my longs as well...  Def leaving a lot of logging behind.

Paste of longing below, for when you do tinker...


6/24/2020, 6:25:21 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:21 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:21 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:21 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:21 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:21 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:21 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:21 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:21 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:21 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:21 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:21 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 70)
6/24/2020, 6:25:26 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:26 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:26 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:26 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:26 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:26 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:26 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:26 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:26 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:26 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:26 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:26 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 71)
6/24/2020, 6:25:31 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:31 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:31 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:31 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:31 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:31 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:31 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:31 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:31 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:31 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:31 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:31 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 72)
6/24/2020, 6:25:35 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:35 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:35 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:35 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:35 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:35 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:35 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:35 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:35 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:35 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:35 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:35 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 73)
6/24/2020, 6:25:41 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:41 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:41 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:41 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:41 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:41 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:41 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:41 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:41 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:41 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:41 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:41 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 74)
6/24/2020, 6:25:46 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:46 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:46 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:46 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:46 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:46 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:46 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:46 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:46 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:46 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:46 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:46 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 75)
6/24/2020, 6:25:51 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:51 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:51 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:51 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:51 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:51 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:51 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:51 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:51 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:51 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:51 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:51 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 76)
6/24/2020, 6:25:55 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:25:55 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:25:55 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:25:55 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:25:55 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:25:55 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:55 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:25:55 PM at Request.emit (events.js:310:20)
6/24/2020, 6:25:55 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:25:55 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:25:55 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:25:55 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 77)
6/24/2020, 6:26:01 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:01 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:01 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:01 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:01 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:01 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:01 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:01 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:01 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:01 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:01 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:01 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78)
6/24/2020, 6:26:05 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:05 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:05 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:05 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:05 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:05 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:05 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:05 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:05 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:05 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:05 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:05 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 79)
6/24/2020, 6:26:11 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:11 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:11 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:11 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:11 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:11 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:11 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:11 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:11 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:11 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:11 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:11 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 80)
6/24/2020, 6:26:16 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:16 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:16 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:16 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:16 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:16 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:16 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:16 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:16 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:16 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:16 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:16 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 81)
6/24/2020, 6:26:21 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:21 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:21 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:21 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:21 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:21 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:21 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:21 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:21 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:21 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:21 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:21 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 82)
6/24/2020, 6:26:26 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:26 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:26 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:26 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:26 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:26 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:26 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:26 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:26 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:26 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:26 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:26 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 83)
6/24/2020, 6:26:30 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:30 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:30 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:30 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:30 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:30 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:30 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:30 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:30 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:30 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:30 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:30 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 84)
6/24/2020, 6:26:36 PM (node:639) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "{\"Error\":{\"Code\":404,\"Message\":\"Foundation is not connected or not working properly\"}}"
6/24/2020, 6:26:36 PM at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
6/24/2020, 6:26:36 PM at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
6/24/2020, 6:26:36 PM at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
6/24/2020, 6:26:36 PM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
6/24/2020, 6:26:36 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:36 PM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
6/24/2020, 6:26:36 PM at Request.emit (events.js:310:20)
6/24/2020, 6:26:36 PM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
6/24/2020, 6:26:36 PM at Object.onceWrapper (events.js:416:28)
6/24/2020, 6:26:36 PM at IncomingMessage.emit (events.js:322:22)
6/24/2020, 6:26:36 PM (node:639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 85)

**Comment by 400HPMustang** [comment] 2020-09-12 14:25
Duplicate of my ticket here https://github.com/DeeeeLAN/homebridge-sleepiq/issues/13

It's just a minor annoyance to have it in the logs but doesn't seem to be impacting functionality at the moment.

**Comment by DeeeeLAN** [comment] 2020-09-17 09:35
I am hoping I have all of these fixed now. Let me know if you find any after updating.

**Closed as completed by DeeeeLAN** 2020-09-17 09:35 UTC
Labels: bug
